In [74]:
import torch
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    # z.numpy() this gives a error, because numpy can only handle CPU tensors! 
    z = z.to("cpu")
    z.numpy() # now, it works!

In [ ]:
x = torch.empty(2, 2, 2, 3, 4)
y = torch.ones(2, 2, dtype=torch.float16)
y = torch.zeros(2, 2)
a = y.dtype
x.size()

elem = torch.tensor([2.5, 1.1])
rand = torch.rand(2, 2)
# both are the same thing
sum = elem + rand
sum = torch.add(elem, rand)
print(elem)
elem.add(y) # the same for sub, mul, div

In [67]:
# getting the rows and columns
p = torch.rand(5, 3)
print(p)
print(p[0,:]) # row 1
print(p[:,0]) # column 1
print(p[2,:]) # row 3

print(p[2,2]) # getting only 1 
print(p[2,2].item()) # this only works if the tensor only has ONE item 

q = p.view(15)
q

tensor([[0.5175, 0.3798, 0.4929],
        [0.8544, 0.8964, 0.2010],
        [0.1450, 0.0641, 0.3229],
        [0.6447, 0.8096, 0.7482],
        [0.9771, 0.1194, 0.2660]])
tensor([0.5175, 0.3798, 0.4929])
tensor([0.5175, 0.8544, 0.1450, 0.6447, 0.9771])
tensor([0.1450, 0.0641, 0.3229])
tensor(0.3229)
0.3228512406349182


tensor([0.5175, 0.3798, 0.4929, 0.8544, 0.8964, 0.2010, 0.1450, 0.0641, 0.3229,
        0.6447, 0.8096, 0.7482, 0.9771, 0.1194, 0.2660])

In [71]:
# converting numpy to tensor / tensor to numpy
import numpy as np

a = torch.zeros(5)
print(type(a))
b = a.numpy()
print(type(b))

a.add_(1)
print(a)
print(b)
# this give the same result because a and b point to the same location in the GPU 

c = np.ones(5)
d = torch.from_numpy(c)
print(type(c))
print(type(d))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [77]:
# by default, requires_grad is False. This will tell torch that he will need
# to calculate the gradient to this tensor later in the optimizations steps
f = torch.ones(5, requires_grad=True)
f

tensor([1., 1., 1., 1., 1.], requires_grad=True)