In [1]:
%config IPCompleter.greedy=True

In [4]:
import torch
import numpy as np

In [5]:
x = torch.randn(3, requires_grad=True)  # requiresgrad makes z backward works
print(x)

y = x + 2
print(y)

z = y * y * 2
print(z)

z = z.mean()
z

z.backward()  # dz/dx


tensor([ 0.0223, -1.3008,  0.5185], requires_grad=True)
tensor([2.0223, 0.6992, 2.5185], grad_fn=<AddBackward0>)
tensor([ 8.1795,  0.9779, 12.6858], grad_fn=<MulBackward0>)


In [10]:
a = torch.randn(3, requires_grad=True)
print(a)

a.requires_grad_(False) # When there is a underline in the sufix of a torch method, it is saying that the result it's applying on the variable 
print(a)
a.requires_grad_(True)
print(a)
b = a.detach()
print(b)

with torch.no_grad():
    c = x + 2
    print(c)

tensor([0.6704, 0.3328, 0.2494], requires_grad=True)
tensor([0.6704, 0.3328, 0.2494])
tensor([0.6704, 0.3328, 0.2494], requires_grad=True)
tensor([0.6704, 0.3328, 0.2494])
tensor([2.0223, 0.6992, 2.5185])


In [18]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [21]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()